create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 32),
  character_id text not null default 'farmer-sage',
  updated_at timestamptz not null default now()
);

create table if not exists public.farm_saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  author text not null check (char_length(author) between 1 and 32),
  body text not null check (char_length(body) between 1 and 180),
  created_at timestamptz not null default now()
);

create table if not exists public.farm_actions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  action_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.farm_saves enable row level security;
alter table public.chat_messages enable row level security;
alter table public.farm_actions enable row level security;

drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select to authenticated using (true);
drop policy if exists "players own profile" on public.profiles;
create policy "players own profile" on public.profiles for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "players own farm save" on public.farm_saves;
create policy "players own farm save" on public.farm_saves for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "chat readable" on public.chat_messages;
create policy "chat readable" on public.chat_messages for select to authenticated using (true);
drop policy if exists "players send chat" on public.chat_messages;
create policy "players send chat" on public.chat_messages for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "players own actions" on public.farm_actions;
create policy "players own actions" on public.farm_actions for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists chat_messages_created_at_idx on public.chat_messages(created_at desc);
create index if not exists farm_actions_user_created_idx on public.farm_actions(user_id, created_at desc);
